#!/bin/bash
# Daily blog update script - runs at 2 AM

WEBSITE_DIR="/home/soikat/clawd/website"
TODAY=$(date +%Y-%m-%d)
MEMORY_FILE="/home/soikat/clawd/memory/${TODAY}.md"

echo "Running daily blog update for $TODAY"

# Check if today's memory file exists
if [ ! -f "$MEMORY_FILE" ]; then
    echo "No memory file for today, creating one..."
    # Create a basic entry
    cat > "$MEMORY_FILE" << EOF
# $TODAY - Session Memories

## Daily Summary
- Auto-blog generated by cron job

EOF
fi

# Extract key events from memory (first few lines after headers)
EVENTS=$(head -20 "$MEMORY_FILE" 2>/dev/null | grep -E "^##? " | head -5 | sed 's/^##* //')

# Create blog entry HTML
BLOG_ENTRY="<article class=\"bg-slate-900/50 backdrop-blur rounded-2xl p-8 border border-white/5 hover:border-purple-500/30 transition-all duration-300\">
                        <div class=\"flex items-center space-x-4 mb-4\">
                            <span class=\"text-purple-400 text-sm font-medium\">$TODAY</span>
                            <span class=\"text-slate-500 text-sm\">Daily</span>
                        </div>
                        <h3 class=\"text-2xl font-bold text-white mb-3\">📝 Daily Update</h3>
                        <p class=\"text-slate-400 mb-4\">$EVENTS</p>
                    </article>"

# Find the blog section and prepend the new entry
# Look for the first article inside #panel-blog
if grep -q "panel-blog" "$WEBSITE_DIR/index.html"; then
    # Insert after the opening div of blog content
    sed -i "/<div id=\"panel-blog\">/,/<\/div>/{
        /<div class=\"space-y-6\">/a\\
$BLOG_ENTRY
    }" "$WEBSITE_DIR/index.html"
    
    # Copy to served location
    sudo cp "$WEBSITE_DIR/index.html" /var/www/html/index.html
    
    echo "Blog updated successfully!"
else
    echo "Blog section not found in HTML"
fi